method: lm_head_full
tune_lm_head_only: true
use_sot: false
use_deep_supervision: false
use_lora: false
use_sdt: false
sdt: false
ds_adaptive: false
train_all_peft: false
peft: null
model: state-spaces/mamba-130m
data: glue_rte
num_epochs: 10
batch_size: 4
learning_rate: 0.02
no_save: false
prec: bf16
seed: 88
output_dir: outputs/lm_head_full/mamba-130m/glue_rte/seed88
