method: sdft
batch_size: 4
data: glue_rte
learning_rate: 0.001
model: state-spaces/mamba-130m
no_save: false
num_epochs: 10
output_dir: outputs/sdft/mamba-130m/glue_rte/seed88
peft: cfg/final/peft/mamba-130m/glue_rte/sdft.json
prec: bf16
seed: 88
use_deep_supervision: false
