batch_size: 4
data: glue_mnli
learning_rate: 0.0004
model: state-spaces/mamba-130m
no_save: false
num_epochs: 3
peft: cfg/final/peft/mamba-130m/glue_mnli/ksot.json
prec: bf16
output_dir: outputs/glue/mnli/ksot
