batch_size: 4
data: glue_sst2
learning_rate: 0.0001
model: state-spaces/mamba-130m
no_save: false
num_epochs: 10
peft: cfg/final/peft/mamba-130m/glue_sst2/ksot.json
prec: bf16
output_dir: outputs/glue/sst2/ksot
